# fly.toml app configuration file generated for sports-intel-api on 2026-03-10T17:15:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sports-intel-api'
primary_region = 'ord'

[build]
  dockerfile = "backend/Dockerfile"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
